-- user seeding
insert into user (name) values ('vijay suriya');
insert into user (name) values ('Aarav Sharma');
insert into user (name) values ('Sneha Patel');
insert into user (name) values ('Priya Singh');
insert into user (name) values ('Rajesh Kumar');
insert into user (name) values ('Deepak Yadav');
insert into user (name) values ('Ananya Mishra');
insert into user (name) values ('Vikram Reddy');
insert into user (name) values ('Kavya Nair');
insert into user (name) values ('Elias Jamil');
insert into user (name) values ('Sophia Rodriguez');
insert into user (name) values ('Liam Johnson');
insert into user (name) values ('Olivia Smith');
insert into user (name) values ('Noah Williams');
insert into user (name) values ('Emma Brown');
insert into user (name) values ('Mason Davis');
insert into user (name) values ('Ava Garcia');
insert into user (name) values ('James Miller');
insert into user (name) values ('Isabella Wilson');
insert into user (name) values ('Benjamin Moore');
insert into user (name) values ('Charlotte Taylor');
insert into user (name) values ('Ethan Anderson');
insert into user (name) values ('Amelia Thomas');
insert into user (name) values ('Alexander Jackson');
insert into user (name) values ('Harper White');
insert into user (name) values ('Jacob Harris');
insert into user (name) values ('Evelyn Martin');
insert into user (name) values ('Michael Thompson');
insert into user (name) values ('Abigail Jones');
insert into user (name) values ('Daniel Lee');
insert into user (name) values ('Emily Clark');
insert into user (name) values ('Henry Hall');
insert into user (name) values ('Elizabeth Lewis');
insert into user (name) values ('Chloe Perez');
insert into user (name) values ('William Young');
insert into user (name) values ('Aisha Khan');
insert into user (name) values ('Fatimah Almas');
insert into user (name) values ('Ahmed Hassan');
insert into user (name) values ('Yusuf Ibrahim');
insert into user (name) values ('Kenji Tanaka');
insert into user (name) values ('Akira Suzuki');
insert into user (name) values ('Yui Kobayashi');
insert into user (name) values ('Daiki Sato');
insert into user (name) values ('Hana Kim');
insert into user (name) values ('Jimin Park');
insert into user (name) values ('Minho Lee');
insert into user (name) values ('Elena Ivanova');
insert into user (name) values ('Dmitri Petrov');
insert into user (name) values ('Svetlana Volkov');
insert into user (name) values ('Ricardo Mendes');
insert into user (name) values ('Camila Rocha');
insert into user (name) values ('Mateus Santos');
insert into user (name) values ('Sofia Fernandez');
insert into user (name) values ('Javier Lopez');
insert into user (name) values ('Catalina Torres');
insert into user (name) values ('Diego Ramirez');
insert into user (name) values ('Chen Wei');
insert into user (name) values ('Li Mei');
insert into user (name) values ('Wang Chao');
insert into user (name) values ('Zhao Ling');
insert into user (name) values ('Jean-Pierre Dubois');
insert into user (name) values ('Sophie Martin');
insert into user (name) values ('Antoine Lefevre');
insert into user (name) values ('Marie Moreau');
insert into user (name) values ('Lukas Müller');
insert into user (name) values ('Hanna Schmidt');
insert into user (name) values ('Tobias Fischer');
insert into user (name) values ('Ida Jensen');
insert into user (name) values ('Magnus Larsen');
insert into user (name) values ('Astrid Olsen');
insert into user (name) values ('Giovanni Rossi');
insert into user (name) values ('Chiara Ferrari');
insert into user (name) values ('Marco Ricci');
insert into user (name) values ('Nadia Khan');
insert into user (name) values ('Samira Hussain');
insert into user (name) values ('Farid Malik');
insert into user (name) values ('Rina Takahashi');
insert into user (name) values ('Kenjiro Ito');
insert into user (name) values ('Aya Yamamoto');
insert into user (name) values ('Elijah Gentry');
insert into user (name) values ('Hannah Blake');
insert into user (name) values ('Owen Reid');
insert into user (name) values ('Stella Price');
insert into user (name) values ('Caleb Scott');
insert into user (name) values ('Penelope King');
insert into user (name) values ('Leo Baker');
insert into user (name) values ('Aurora Carter');
insert into user (name) values ('Julian Foster');
insert into user (name) values ('Violet Hayes');
insert into user (name) values ('Gabriel Cole');
insert into user (name) values ('Ruby Ross');
insert into user (name) values ('Hunter Bell');
insert into user (name) values ('Skylar Cooper');
insert into user (name) values ('Adrian Cox');
insert into user (name) values ('Nova Perry');
insert into user (name) values ('Silas Ward');
insert into user (name) values ('Luna Brooks');
insert into user (name) values ('Zane Powell');
insert into user (name) values ('Willow Murphy');
insert into user (name) values ('Victor Hughes');
insert into user (name) values ('Piper Evans');

-- seat seeding
insert into seat (seat) values ('1A');
insert into seat (seat) values ('1B');
insert into seat (seat) values ('1C');
insert into seat (seat) values ('1D');
insert into seat (seat) values ('1E');
insert into seat (seat) values ('1F');
insert into seat (seat) values ('2A');
insert into seat (seat) values ('2B');
insert into seat (seat) values ('2C');
insert into seat (seat) values ('2D');
insert into seat (seat) values ('2E');
insert into seat (seat) values ('2F');
insert into seat (seat) values ('3A');
insert into seat (seat) values ('3B');
insert into seat (seat) values ('3C');
insert into seat (seat) values ('3D');
insert into seat (seat) values ('3E');
insert into seat (seat) values ('3F');
insert into seat (seat) values ('4A');
insert into seat (seat) values ('4B');
insert into seat (seat) values ('4C');
insert into seat (seat) values ('4D');
insert into seat (seat) values ('4E');
insert into seat (seat) values ('4F');
insert into seat (seat) values ('5A');
insert into seat (seat) values ('5B');
insert into seat (seat) values ('5C');
insert into seat (seat) values ('5D');
insert into seat (seat) values ('5E');
insert into seat (seat) values ('5F');
insert into seat (seat) values ('6A');
insert into seat (seat) values ('6B');
insert into seat (seat) values ('6C');
insert into seat (seat) values ('6D');
insert into seat (seat) values ('6E');
insert into seat (seat) values ('6F');
insert into seat (seat) values ('7A');
insert into seat (seat) values ('7B');
insert into seat (seat) values ('7C');
insert into seat (seat) values ('7D');
insert into seat (seat) values ('7E');
insert into seat (seat) values ('7F');
insert into seat (seat) values ('8A');
insert into seat (seat) values ('8B');
insert into seat (seat) values ('8C');
insert into seat (seat) values ('8D');
insert into seat (seat) values ('8E');
insert into seat (seat) values ('8F');
insert into seat (seat) values ('9A');
insert into seat (seat) values ('9B');
insert into seat (seat) values ('9C');
insert into seat (seat) values ('9D');
insert into seat (seat) values ('9E');
insert into seat (seat) values ('9F');
insert into seat (seat) values ('10A');
insert into seat (seat) values ('10B');
insert into seat (seat) values ('10C');
insert into seat (seat) values ('10D');
insert into seat (seat) values ('10E');
insert into seat (seat) values ('10F');
insert into seat (seat) values ('11A');
insert into seat (seat) values ('11B');
insert into seat (seat) values ('11C');
insert into seat (seat) values ('11D');
insert into seat (seat) values ('11E');
insert into seat (seat) values ('11F');
insert into seat (seat) values ('12A');
insert into seat (seat) values ('12B');
insert into seat (seat) values ('12C');
insert into seat (seat) values ('12D');
insert into seat (seat) values ('12E');
insert into seat (seat) values ('12F');
insert into seat (seat) values ('14A'); /* Skipping 13 for superstition */
insert into seat (seat) values ('14B');
insert into seat (seat) values ('14C');
insert into seat (seat) values ('14D');
insert into seat (seat) values ('14E');
insert into seat (seat) values ('14F');
insert into seat (seat) values ('15A');
insert into seat (seat) values ('15B');
insert into seat (seat) values ('15C');
insert into seat (seat) values ('15D');
insert into seat (seat) values ('15E');
insert into seat (seat) values ('15F');
insert into seat (seat) values ('16A');
insert into seat (seat) values ('16B');
insert into seat (seat) values ('16C');
insert into seat (seat) values ('16D');
insert into seat (seat) values ('16E');
insert into seat (seat) values ('16F');
insert into seat (seat) values ('17A');
insert into seat (seat) values ('17B');
insert into seat (seat) values ('17C');
insert into seat (seat) values ('17D');
insert into seat (seat) values ('17E');
insert into seat (seat) values ('17F');
insert into seat (seat) values ('18A');
insert into seat (seat) values ('18B');
insert into seat (seat) values ('18C');
insert into seat (seat) values ('18D');
insert into seat (seat) values ('18E');